spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-authentication-method: client_secret_post
            redirect-uri: ${kakao.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    contentnegotiation:
      default-content-type: application/json
    jackson:
      default-property-inclusion: non_null
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # TODO: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug
    com.bankersCalculator.server: debug

jwt:
  secret-key: ${jwt.secret-key} # TODO: change to UUID
  access-token-validity-in-seconds: 36000
  refresh-token-validity-in-seconds: 86400
