spring:
  ai:
    openai:
      api-key: ${ai.openai.api-key}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-authentication-method: client_secret_post
            redirect-uri: ${kakao.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    contentnegotiation:
      default-content-type: application/json
    jackson:
      default-property-inclusion: non_null
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: false
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:~/test
#    username: sa
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
        stat: DEBUG
        event:
          internal: TRACE
        transaction: DEBUG
      springframework:
        transaction: TRACE

jwt:
  secret-key: ${jwt.secret-key} # TODO: change to UUID
  access-token-validity-in-seconds: 36000
  refresh-token-validity-in-seconds: 86400

cloud:
  aws:
    credentials:
      access-key: AKIATAVAA3FNYHXWF775
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: myzipplan-service-storage

app:
  redirect-uri-base: ${REDIRECT_URI_BASE:http://localhost:5173}