spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            redirect-uri: ${kakao.redirect-uri}


jwt:
#  secret-key: ${jwt.secret_key} // TODO: UUID ??? ?
  secret-key: "secretsecret"
  access-token-validity-in-seconds: 30000
  refresh-token-validity-in-seconds: 86400