spring:
  ai:
    openai:
      api-key: ${ai.openai.api-key}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            client-authentication-method: client_secret_post
            redirect-uri: ${kakao.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    contentnegotiation:
      default-content-type: application/json
    jackson:
      default-property-inclusion: non_null
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    hikari:
      maximum-pool-size: 15
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
    root: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG

jwt:
  secret-key: ${jwt.secret-key} # TODO: change to UUID
  access-token-validity-in-seconds: 36000
  refresh-token-validity-in-seconds: 86400

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:AKIAT4GVSAAD4DUWG7FL}
      secret-key: ${AWS_SECRET_KEY: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}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET:myzipplan-service-storage-dev}

app:
  redirect-uri-base:
    prod: ${https://myzipplan.com}
    dev: ${http://localhost:5173}


discord:
  webhook:
    url: "https://discord.com/api/webhooks/1316397029789925447/yB3jx6r54lGlmtVSpo8zZNYUBu3kGAxgQevv4gvUm6IbwROiw6owHI9HEYNYpw_DMvPc"