name: Health Check and Notify

on:
  schedule:
    - cron: '*/5 * * * *' # 매 5분마다 실행

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Perform Health Check
      run: |
        if curl -fsS https://myzipplan.com/community | grep "status: healthy"; then
          echo "Health check passed."
        else
          echo "Health check failed."
          exit 1
        fi

    - name: Notify Discord
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "**Health Check Failed!**\nCheck the system immediately!"}' \
          https://discord.com/api/webhooks/1316397029789925447/yB3jx6r54lGlmtVSpo8zZNYUBu3kGAxgQevv4gvUm6IbwROiw6owHI9HEYNYpw_DMvPc
